### ISSUE TITLE
Cute

### ISSUE THREAD

**Issue by mesaugat** [srishanbhattarai/flipgit#1]
**I did this instead.**

<img width="1034" alt="screen shot 2018-05-18 at 8 25 59 am" src="https://user-images.githubusercontent.com/4240991/40213438-26e6f07a-5a75-11e8-91fc-ff54c134423a.png">

**Comment by srishanbhattarai** [comment]
Do not want. 😸

**Comment by mesaugat** [comment]
Ain't nobody got time for 'Your teams'. **REMOVE!**

**Comment by srishanbhattarai** [comment]
I just need the feed to be on the left, nothing else matters 🗡

**Comment by srishanbhattarai** [comment]
But willing to accept a PR @mesaugat  😄
